networks:
    nginx-proxy-manager: 
      external:
        name: nginx-proxy-manager

services:
    app:
        depends_on:
            - ui
        build:
            context: ./backend
            dockerfile: Dockerfile.prod
        image: ganslider:lts
        deploy:
            resources:
              reservations:
                devices:
                - capabilities: [gpu]
        volumes:
            - $PWD/backend:/app
            - $PWD/frontend/build:/frontend/public
        environment:
            - GANSLIDER_DEBUGGING=${GANSLIDER_DEBUGGING}
            - PROLIFIC_STUDY_ID=${PROLIFIC_STUDY_ID}
            - GANSLIDER_ROOT_DIR=${GANSLIDER_ROOT_DIR}
            - GANSLIDER_LOG_DATABASE=${GANSLIDER_LOG_DATABASE}
        networks:
            - nginx-proxy-manager
    ui:
        build:
            context: ./frontend
            dockerfile: Dockerfile.prod
        image: ganslider-ui:lts
        volumes:
            - $PWD/frontend/build/:/ui/build/
            - $PWD/frontend/public:/ui/public
            - $PWD/frontend/src/:/ui/src/
        environment:
            - REACT_APP_GANSLIDER_DEBUGGING=${GANSLIDER_DEBUGGING}
            - REACT_APP_ROOT_DIR=${GANSLIDER_ROOT_DIR}
            - REACT_APP_PROLIFIC_URL=${GANSLIDER_PROLIFIC_CALLBACK}
            - PUBLIC_URL=${GANSLIDER_PUBLIC_URL}
    mongodb:
        image: mongo
        volumes:
            - $HOME/mongodb/database:/data/db
        networks:
            - nginx-proxy-manager
    ganspace_slider_nginx:
        image: nginx
        ports:
            - 8888:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - $PWD/frontend/build:/frontend/public
        depends_on:
            - app
        networks:
            - nginx-proxy-manager
