FROM nvcr.io/nvidia/pytorch:20.01-py3

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY src/ src/
COPY ganspace/ ganspace/
COPY server.py server.py

CMD ["uvicorn", "server:app", "--workers", "1", "--host", "0.0.0.0", "--port", "8000"]
